# Generated by Django 6.1.1 on 2026-09-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('format_version', models.PositiveIntegerField(default=1)),
                ('item_version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='files.filefolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='accounts.user')),
            ],
            options={
                'db_table': 'files_filefolder',
            },
        ),
        migrations.AddField(
            model_name='storedfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.filefolder'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['user', 'folder'], name='files_store_user_id_ada1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='filefolder',
            index=models.Index(fields=['user', 'parent'], name='files_filef_user_id_3fbedd_idx'),
        ),
    ]
