# Generated by Django 6.1.1 on 2026-09-15 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFolder',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('format_version', models.PositiveIntegerField(default=1)),
                ('item_version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='notes.notefolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_folders', to='accounts.user')),
            ],
            options={
                'db_table': 'notes_notefolder',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.notefolder'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'folder'], name='notes_note_user_id_1f7e93_idx'),
        ),
        migrations.AddIndex(
            model_name='notefolder',
            index=models.Index(fields=['user', 'parent'], name='notes_notef_user_id_a4617e_idx'),
        ),
    ]
